version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env
    volumes:
      - ./_data/mongo:/data/db
      - ./docker/_mongo/fixtures:/import
      - ./docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - '27017:27017'

  postgres:
    container_name: postgres
    image: postgres:14
    restart: on-failure
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
      - ./docker/_postgres/scripts/create_test_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER' ]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - '6379'

  app:
    build: .
    image: app:latest
    container_name: app
    tty: true
    restart: on-failure
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: [
            "celery",
            "-A",
            "config",
            "worker",
            "-c",
            "1",
            "-l",
            "INFO",
            "--without-heartbeat",
            "--without-gossip",
            "--without-mingle",
          ]

    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
      - postgres
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_WSGI=config.wsgi
      - DEBUG=False

volumes:
  pg_data:
networks:
  default: